version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
  redis:
    image: redis
  postgres_api:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/test_db
      - SECRET_KEY=flytospace
      - DEV_MODE=True
      - REDIS_URL=redis://redis:6379
      - LIMITER_ENABLED=True
    depends_on:
      - db
      - redis